theme: minima
title: dkc's GitHub.io
author: dkc
description: There is no spoon.
github_username:  askdkc

minima:
  date_format: "%Y-%m-%d %H:%M"

  social_links:
    - { platform: github,         user_url: "https://github.com/askdkc" }